#Joao Classio 09/22/2025 joaoClassioPE5_3.py

#This program will draw a snow man using turtle

#Importing turtle and configuring it 
import turtle
turtle.speed(0)
turtle.width(3)
turtle.bgcolor("light gray")

def drawBase(): #Draws the base
    turtle.penup()
    turtle.goto(0,-300)
    turtle.pendown()
    turtle.circle(100)

def drawMidSection(): #Draws the mid section
    turtle.penup()
    turtle.goto(0,-100)
    turtle.pendown()
    turtle.circle(66)
    
def drawArms(): #Draws the arms
    turtle.penup()
    turtle.goto(-66,-33)
    turtle.pendown()
    turtle.setheading(170)
    turtle.forward(65)
    turtle.right(60)
    turtle.forward(50)
    turtle.right(20)
    turtle.forward(10)
    turtle.backward(10)
    turtle.left(70)
    turtle.forward(10)    
    turtle.penup()
    turtle.goto(66,-33)
    turtle.pendown()
    turtle.setheading(30)
    turtle.forward(65)
    turtle.right(20)
    turtle.forward(10)
    turtle.backward(10)
    turtle.left(70)
    turtle.forward(10)    

    
def drawHead(): #Draws the head
    turtle.penup()
    turtle.goto(32,57)
    turtle.pendown()
    turtle.circle(33)
    turtle.penup()
    turtle.goto(-16,55)
    turtle.pendown()
    turtle.setheading(0)
    turtle.forward(32)
    turtle.penup()
    turtle.goto(-10,66)
    turtle.pendown()
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(10,66)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()

def drawHat(): #Draws the hat
    turtle.penup()
    turtle.goto(-60,80)
    turtle.pendown()
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.setheading(0)
    turtle.forward(120)
    turtle.left(90)
    turtle.forward(20) #lado menor ratangulo
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.end_fill()
    
def drawButton(): #Draws the buttons
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,0)
    turtle.pendown()
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-30)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-60)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-90)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
       
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-120)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill() 
    
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-150)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-180)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
    turtle.setheading(0)
    turtle.penup()
    turtle.goto(0,-210)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    
def drawScarf(): #Draws the scarf
    turtle.pencolor("dark red")
    turtle.setheading(320)
    turtle.penup()
    turtle.goto(-33,50)
    turtle.pendown()
    turtle.fillcolor('red')
    turtle.begin_fill()
    turtle.circle(50, extent = 80)    
    turtle.setheading(270)
    turtle.forward(30)
    turtle.setheading(45)
    turtle.circle(60, extent = -80)
    turtle.goto(-33,50)
    turtle.end_fill()
    
    
#Calling the methods 
drawBase()
drawMidSection()
drawArms()
drawHead()
drawHat()
drawButton()
drawScarf()

turtle.done()    
    